# 应用服务 WEB 访问端口
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/express?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: chenchen@2016150056
mybatis:
  config-location: classpath:config.xml

